# Generated by Django 6.0.2 on 2026-03-03 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patient_is_approved_accountapprovalrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='appointment_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='upcoming_appointments',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='appointment_schedule',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='patient_list',
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptionists', to='accounts.provider'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.provider')),
            ],
        ),
    ]
