# Generated by Django 6.0.2 on 2026-04-08 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_successstory'),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labstaff',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.lab'),
        ),
    ]
